const bankOne = [
  {
    id: 0,
    keyCode: 81,
    keyTrigger: "Q",
    name: "Heater-1",
    url: "https://s3.amazonaws.com/freecodecamp/drums/Heater-1.mp3",
    url_2: "https://s3.amazonaws.com/freecodecamp/drums/Chord_1.mp3",
  },
  {
    id: 1,
    keyCode: 87,
    keyTrigger: "W",
    name: "Heater-2",
    url: "https://s3.amazonaws.com/freecodecamp/drums/Heater-2.mp3",
    url_2: "https://s3.amazonaws.com/freecodecamp/drums/Chord_2.mp3",
  },
  {
    id: 2,
    keyCode: 69,
    keyTrigger: "E",
    name: "Heater-3",
    url: "https://s3.amazonaws.com/freecodecamp/drums/Heater-3.mp3",
    url_2: "https://s3.amazonaws.com/freecodecamp/drums/Chord_3.mp3",
  },
  {
    id: 3,
    keyCode: 65,
    keyTrigger: "A",
    name: "Heater-4",
    url: "https://s3.amazonaws.com/freecodecamp/drums/Heater-4_1.mp3",
    url_2: "https://s3.amazonaws.com/freecodecamp/drums/Give_us_a_light.mp3",
  },
  {
    id: 4,
    keyCode: 83,
    keyTrigger: "S",
    name: "Clap",
    url: "https://s3.amazonaws.com/freecodecamp/drums/Heater-6.mp3",
    url_2: "https://s3.amazonaws.com/freecodecamp/drums/Dry_Ohh.mp3",
  },
  {
    id: 5,
    keyCode: 68,
    keyTrigger: "D",
    name: "Open-HH",
    url: "https://s3.amazonaws.com/freecodecamp/drums/Dsc_Oh.mp3",
    url_2: "https://s3.amazonaws.com/freecodecamp/drums/Bld_H1.mp3",
  },
  {
    id: 6,
    keyCode: 90,
    keyTrigger: "Z",
    name: "Kick-n'-Hat",
    url: "https://s3.amazonaws.com/freecodecamp/drums/Kick_n_Hat.mp3",
    url_2: "https://s3.amazonaws.com/freecodecamp/drums/punchy_kick_1.mp3",
  },
  {
    id: 7,
    keyCode: 88,
    keyTrigger: "X",
    name: "Kick",
    url: "https://s3.amazonaws.com/freecodecamp/drums/RP4_KICK_1.mp3",
    url_2: "https://s3.amazonaws.com/freecodecamp/drums/side_stick_1.mp3",
  },
  {
    id: 8,
    keyCode: 67,
    keyTrigger: "C",
    name: "Closed-HH",
    url: "https://s3.amazonaws.com/freecodecamp/drums/Cev_H2.mp3",
    url_2: "https://s3.amazonaws.com/freecodecamp/drums/Brk_Snr.mp3",
  },
];
export default bankOne;
